### PR TITLE
Add error handler middleware

### LINKED ISSUE #236: Catogorize error type and add error handler middleware
## Introduction
Catogorized error type and add error handler middleware

## Issues / Motivations
- Error response is hard to read for users

image

## Proposals / Solutions
- Define different error types in model
- Add a universal error handler middleware that tackle different error types

## Work Plan
- [ ] Error types
  - 401 token invalid
  - 403 forbidden, token user not have access
  - 404 not found: detail message
  - 400 bad request: detail message
  - 500 interal error
- [ ] Error handler
  - res.status(code)
  - res.send(error_message)

## Test cases
#214

### PR DESCRIPTION
**Pull request by debuggy**
closes #236 

1. Create several error type based on https://github.com/jshttp/http-errors#list-of-all-constructors

2. Add a universal error handler middleware for all errors

3. Refactor controller with new error models

### CODE REVIEW

**Review by SwordFaith — APPROVED** [review]

**Comment by SwordFaith** [comment]
In current implementation, if isPrivate == true but  groupList is not null and have overlap with specific user, the item can be accessed by the user, is that a logic bug ?

**Comment by SwordFaith** [comment]
For storage/blobs on 177 bed has 404 not found for both admin token and normal user token

**Comment by debuggy** [comment]
> For storage/blobs on 177 bed has 404 not found for both admin token and normal user token
> image

should be /storages/blobs

**Comment by debuggy** [comment]
> In current implementation, if isPrivate == true but groupList is not null and have overlap with specific user, the item can be accessed by the user, is that a logic bug ?

could create a new bug report and fix it in models logic

**Pull request merged**
