### PR TITLE
Update tags and categories of the examples

### PR DESCRIPTION
**Pull request by yiyione**
Add category `"official example"` to all examples.

### CODE REVIEW

**Comment by hippogr** [comment]
should you change other item's tag to make it more meaningful? For instance, this one:
    id: "69ff3c37-1405-49a7-b9de-47e640ba490c",
    name: "Caffe2 Minist Job Template",
    author: "OpenPAI",
    type: "old",
    categories: ["official example"],
    tags: ["official example"],

how about changing the tag to "Caffe2 Minist"?

**Review by hippogr — APPROVED** [review]

**Review by debuggy — APPROVED** [review]

**Comment by yiyione** [comment]
> should you change other item's tag to make it more meaningful? For instance, this one:
> id: "69ff3c37-1405-49a7-b9de-47e640ba490c",
> name: "Caffe2 Minist Job Template",
> author: "OpenPAI",
> type: "old",
> categories: ["official example"],
> tags: ["official example"],
> 
> how about changing the tag to "Caffe2 Minist"?

Added meaningful tags for them.

**Comment by yiyione** [comment]
Hi @hippogr @debuggy , I added some meaningful tags for other examples, and it dismissed stale reviews.
Could you please review again? Thanks.

**Review by debuggy — APPROVED** [review]

**Review by hippogr — APPROVED** [review]
:shipit:

**Pull request merged**
